/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.akproductions;

import com.google.common.collect.Lists;

import java.util.ArrayList;
import java.util.List;

import java.util.Random;
import java.util.Scanner;
import com.google.common.base.Joiner;

/**
 * To start the application:
 * ./gradlew build
 * java -jar ./L01-gradle/build/libs/gradleHelloWorld-0.1.jar
 * <p>
 * To unzip the jar:
 * unzip -l L01-gradle.jar
 * unzip -l gradleHelloWorld-0.1.jar
 * <p>
 * To build:
 * ./gradlew build
 */
public class HelloOtus {
    public static void main(String... args) throws Exception {
        /*
        List<Integer> example = new ArrayList<>();
        int min = 0;
        int max = 100;
        for (int i = min; i < max; i++) {
            example.add(i);
        }
        System.out.println(Lists.reverse(example));
*/
        Joiner joiner=Joiner.on("");
        System.out.println(joiner.join("Call of"," guava joiner!!!"));
        try {
            Scanner scn = new Scanner(System.in);
            Random r = new Random();
            int boundVar = 100;
            int x = r.nextInt(boundVar) + 1, z, counter = 0;
            System.out.print("Guess number! \n");
            do {
                System.out.print(joiner.join("Enta numba from 1 to ",(boundVar+1)," to play or sheet to exit - step " , (7 - counter) , ": "));
                z = scn.nextInt();
                if (z > x)
                    System.out.println(joiner.join("2much - human entered " , z ," ML supposed ??"));
                if (z < x)
                    System.out.println(joiner.join("2small - human entered " , z , " ML supposed ??"));
                counter++;
            }
            while ((z != x) && (counter < 7));
            if (z == x)
                System.out.print("Cool, Dude! ");
            else
                System.out.print("Loser! ML supposed "+x + "\n");

        } catch (Exception exp) {
            System.out.println("Have a nice day!!!");
        }
    }
}
